Replace org.apache.log4j package import by bundle dependency
Tycho picks some org.slf4j bundles to satisfy our package dependency
to org.apache.log4j needed to run swtbot tests. This caused a
NoClassDefFoundError due to some additional dependencies slf4j has.
Switching to a bundle dependency fixes this problem.

Change-Id: Ib9e70312bcdd591ec874cea0d10140300446cf93
Signed-off-by: Matthias Sohn <matthias.sohn@sap.com>